//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Course.cpp
//  @ Date : 16.05.2024
//  @ Author : 
//
//


#include "Course.h"

Course::Course(string name, int capacity) {
    this->name=name;
    this->capacity=capacity;
}

bool Course::addGrade(Student* student, float grade) {
    grades[student].push_back(grade);
    return true;
}

bool Course::addStudent(Student* student) {
    if(this->currentCapacity<this->capacity)
    {
        for(int i=0;i<students.size();++i)
        {
            if(students[i]==student)
            {
                return false;
            }
        }
        currentCapacity++;
        students.push_back(student);
        return true;
    }
    else
    return false;
}

void Course::setMaterials(string file) {
    this->materials=file;
}

string Course::getMaterials() {
    return this->materials;
}

map<Student*,vector<float>> Course::getGrades() {
    return this->grades;
}

string Course::getName() {
    return this->name;
}

vector<Student*> Course::getStudents() {
    return this->students;
}

