//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Department.cpp
//  @ Date : 16.05.2024
//  @ Author : 
//
//


#include "Department.h"
#include "Course.h"

Department::Department(string name) {
    this->name=name;
}

bool Department::addTeacher(Teacher* teacher) {
    this->teachers.push_back(teacher);
    return true;
}

bool Department::addCourse(Course* course) {
    for(int i=0;i<courses.size();++i)
    {
        if(courses[i]->getName()==course->getName())
        {
            return false;
        }
    }
    courses.push_back(course);
    return true;
}

string Department::getName() {
    return this->name;
}

vector<Teacher*> Department::getTeachers() {
    return this->teachers;
}

vector<Course*> Department::getCourses() {
    return this->courses;
}

