//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Student.h
//  @ Date : 16.05.2024
//  @ Author : 
//
//


#if !defined(_STUDENT_H)
#define _STUDENT_H

#include <string>
#include <vector>
#include "Department.h"

using namespace std;

class Student {
private:
	string login;
	string password;
    class Department* department;
	string name;
	string surname;
	vector<class Course*> courses;
public:
	Student(string login, string password, string name, string surname, Department* department);
	bool joinCourse(Course* course);
	vector<Course*> getCourses();
	string getLogin();
	string getPassword();
	string getName();
	string getSurname();
	Department* getDepartment();
};

#endif  //_STUDENT_H
