//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : University.h
//  @ Date : 16.05.2024
//  @ Author : 
//
//


#if !defined(_UNIVERSITY_H)
#define _UNIVERSITY_H
#include "Student.h"
#include "Course.h"
class University {
private:
	string name;
	vector<Student*> students;
	vector<Teacher*> teachers;
	vector<Department*> departments;
public:
	University(string name);
	Teacher* LoginTeacher(string login, string password);
	bool RegisterTeacher(string login, string password, string name, string surname, Department* department);
	Student* LoginStudent(string login, string password);
	bool RegisterStudent(string login, string password, string name, string surname, Department* department);
    bool addDepartment(string name);
	vector<Department*> getDepartments();
    string getName();
    vector<Student *> getStudents();
    vector<Teacher *> getTeachers();
};

#endif  //_UNIVERSITY_H
