//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Course.h
//  @ Date : 16.05.2024
//  @ Author : 
//
//


#if !defined(_COURSE_H)
#define _COURSE_H


#include "Student.h"
#include <map>

using namespace std;

class Course {
private:
	string name;
	class Teacher* teacher;
	string materials = "";
	int capacity;
	int currentCapacity = 0;
	vector<class Student*> students;
	map<class Student*,vector<float>> grades;
    class Department* department;
public:
	Course(string name, Teacher* teacher, Department* department, int capacity);
	bool addGrade(Student* student, float grade);
	bool addStudent(Student* student);
	void setMaterials(string file);
	string getMaterials();
	map<Student*,vector<float>> getGrades();
	string getName();
	Teacher* getTeacher();
	vector<Student*> getStudents();
	Department* getDepartment();
};

#endif  //_COURSE_H
