//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Department.h
//  @ Date : 16.05.2024
//  @ Author : 
//
//


#if !defined(_DEPARTMENT_H)
#define _DEPARTMENT_H
#include "Teacher.h"

using namespace std;
class Department {
private:
	string name;
	vector<class Teacher*> teachers;
	vector<class Course*> courses;
public:
	Department(string name);
	bool addTeacher(Teacher* teacher);
	bool addCourse(Course* course);
	string getName();
	vector<Teacher*> getTeachers();
	vector<Course*> getCourses();
};

#endif  //_DEPARTMENT_H
