//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Student.cpp
//  @ Date : 16.05.2024
//  @ Author : 
//
//


#include "Student.h"
#include "Course.h"

Student::Student(string login, string password, string name, string surname, Department* department) {
    this->login=login;
    this->password=password;
    this->name=name;
    this->surname=surname;
    this->department=department;
}

bool Student::joinCourse(Course* course) {
    bool success=course->addStudent(this);
    if(success)
    {
        courses.push_back(course);
    }
    return success;
}

vector<Course*> Student::getCourses() {
    return this->courses;
}

string Student::getLogin() {
    return this->login;
}

string Student::getPassword() {
    return this->password;
}

string Student::getName() {
    return this->name;
}

string Student::getSurname() {
    return this->surname;
}

Department* Student::getDepartment() {
    return this->department;
}

