//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Teacher.cpp
//  @ Date : 16.05.2024
//  @ Author : 
//
//


#include "Teacher.h"
#include "Course.h"

Teacher::Teacher(string login, string password, string name, string surname, Department* department) {
    this->login=login;
    this->password=password;
    this->name=name;
    this->surname=surname;
    this->department=department;
}

bool Teacher::addCourse(string name, int capacity) {
    Course* course=new Course(name,this,this->department,capacity);
    bool success=this->department->addCourse(course);
    if(success)
        this->courses.push_back(course);
    return success;
}

bool Teacher::addGrade(Course* course, Student* student, float grade) {
    return course->addGrade(student,grade);
}

vector<Course*> Teacher::getCourses() {
    return this->courses;
}

string Teacher::getLogin() {
    return this->login;
}

string Teacher::getPassword() {
    return this->password;
}

string Teacher::getName() {
    return this->name;
}

string Teacher::getSurname() {
    return this->surname;
}

Department* Teacher::getDepartment() {
    return this->department;
}

